version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-agent-backend:latest
    container_name: property-agent-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Firebase credentials file
      - ./Firebase_key.json:/app/Firebase_key.json:ro
      # Persistent data
      - backend-data:/app/data
    env_file:
      # Support for multi-environment configuration
      - .env
      # Optional: If there are environment-specific config files
      # - .env.${ENV:-production}
    environment:
      # Environment variables can be defined or overridden here
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

volumes:
  backend-data:
    # Internal volume, automatically created
    driver: local

# Optional: If there are multiple services (such as databases) that need network communication
networks:
  app-network:
    driver: bridge 