version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: property-agent-backend:latest
    container_name: property-agent-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Firebase凭证文件
      - ./Firebase_key.json:/app/Firebase_key.json:ro
      # 持久化数据
      - backend-data:/app/data
    env_file:
      # 支持多环境配置
      - .env
      # 可选：如果有特定环境的配置文件
      # - .env.${ENV:-production}
    environment:
      # 可以在这里定义或覆盖环境变量
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

volumes:
  backend-data:
    # 内部卷，自动创建
    driver: local

# 可选：如果有多个服务（如数据库等）需要网络通信
networks:
  app-network:
    driver: bridge 